name: acquire-artifact-lock
author: guibranco
description: Acquire lock using artifact existence as a locking mechanism

branding:
  icon: lock
  color: green

inputs:
  lock-name:
    description: Name of the lock (used as artifact name)
    required: true
    default: test-lock
  retry-wait:
    description: Seconds to wait before retrying
    required: false
    default: "10"
  retry-max:
    description: Maximum number of retries
    required: false
    default: "30"

runs:
  using: "composite"
  steps:
    - name: Try to acquire lock 🔐
      shell: bash
      run: |
        echo "🔐 Acquiring lock: '${{ inputs.lock-name }}'"

        TOKEN="${{ github.token }}"
        REPO="${{ github.repository }}"
        LOCK_NAME="${{ inputs.lock-name }}"
        API_URL="https://api.github.com/repos/$REPO/actions/artifacts"

        attempt=0
        while [[ $attempt -lt ${{ inputs.retry-max }} ]]; do
          echo "🔍 Checking for existing lock (attempt $((attempt+1))/${{ inputs.retry-max }})..."
          response=$(curl -s \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "$API_URL?name=$LOCK_NAME")

          lock_id=$(echo "$response" | jq -r '.artifacts[0].id')

          if [[ -z "$lock_id" || "$lock_id" == "null" ]]; then
            echo "✅ Lock is free. Proceeding to create artifact lock..."
            mkdir -p _artifact-lock
            echo "locked" > _artifact-lock/lock
            exit 0
          fi

          echo "⏳ Lock is still held. Waiting ${{ inputs.retry-wait }}s before retrying..."
          attempt=$((attempt + 1))
          sleep "${{ inputs.retry-wait }}"
        done

        echo "❌ Failed to acquire lock after ${{ inputs.retry-max }} attempts. Lock ID: $lock_id"
        exit 1

    - name: Upload lock artifact 🔏
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.lock-name }}
        path: _artifact-lock/lock
        retention-days: 1

    - name: Confirm lock acquired ✅
      if: success()
      shell: bash
      run: echo "✅ Lock acquired."
