name: release-artifact-lock
author: guibranco
description: Release lock by deleting the artifact

branding:
  icon: unlock
  color: green

inputs:
  lock-name:
    description: Name of the lock (used as artifact name)
    required: true
    default: test-lock

runs:
  using: "composite"
  steps:
    - name: Release lock 🔓
      shell: bash
      run: |
        echo "🔓 Releasing lock: '${{ inputs.lock-name }}'"

        TOKEN="${{ github.token }}"
        REPO="${{ github.repository }}"
        LOCK_NAME="${{ inputs.lock-name }}"
        API_URL="https://api.github.com/repos/$REPO/actions/artifacts"

        response=$(curl -s -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.github+json" "$API_URL?name=$LOCK_NAME")
        lock_id=$(echo "$response" | jq -r '.artifacts[0].id')

        if [[ -n "$lock_id" && "$lock_id" != "null" ]]; then
          curl -s -X DELETE \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "$API_URL/$lock_id"
          echo "✅ Lock released."
        else
          echo "⚠️ No lock found."
        fi
